services:
  web-ui:
    image: ggmartinez/laravel:php-8.2-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - SKIP_COMPOSER_INSTALL=false
      - SKIP_SEEDERS=true
      - SKIP_MIGRATIONS=false
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_DATABASE=mongo
      - DB_USERNAME=mongo
      - DB_PASSWORD=mongo
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

